'use client';

import styles from './ExperiencesSection.module.css';

export default function ExperiencesSection({ language = 'fr' }) {
  const french = language === 'fr';
  const experiences = [
    { company: 'NTT Data', role: french ? 'Stage — Intelligence artificielle' : 'Internship — Artificial Intelligence', period: french ? 'En cours' : 'Ongoing', desc: french ? 'Conception d’un agent IA de service client interne : classification des e-mails et messages Teams, premières réponses et routage intelligent des demandes.' : 'Designing an internal AI customer-service agent that classifies emails and Teams messages, prepares first responses and routes requests intelligently.', tags: ['Python', 'Microsoft Graph', 'Teams', 'LangChain'], link: 'https://www.nttdata.com', image: '/ntt.png', accent: '#b85f77' },
    { company: '3LM Solutions', role: french ? 'Stage — Superviseur IA' : 'Internship — AI Supervisor', period: french ? 'En cours' : 'Ongoing', desc: french ? 'Développement d’un superviseur IA pour analyser les appels : scoring de qualité, résumés, débriefing post-appel, conseils personnalisés et suivi de progression commerciale.' : 'Building an AI supervisor for call analysis: quality scoring, summaries, post-call debriefing, personalised coaching and sales-progress tracking.', tags: ['NestJS', 'PostgreSQL', 'pgvector', 'Qdrant'], link: 'https://www.3lmsolutions.com', image: '/3LM.jpg', accent: '#9b76a7' },
    { company: 'Commune de Tanger', role: french ? 'Stage technique' : 'Technical internship', period: '2025', desc: french ? 'Développement d’une application mobile de gestion de l’éclairage public, avec géolocalisation et suivi des signalements citoyens.' : 'Development of a mobile public-lighting management application with geolocation and citizen-report tracking.', tags: ['Flutter', 'Geolocation', 'PostgreSQL'], link: 'https://fr.tanger.ma/', image: '/commune.png', accent: '#cb975b' },
    { company: 'Activ Digital', role: french ? 'Stage technique' : 'Technical internship', period: '2024', desc: french ? 'Conception d’une application RH pour centraliser les collaborateurs, les congés et les processus internes autour d’une expérience simple.' : 'Designing an HR application that centralises employees, leave management and internal workflows in a simple experience.', tags: ['React', 'Node.js', 'MongoDB', 'Express.js'], link: 'https://activdigital.ma/#hero', image: '/activ.png', accent: '#cf7389' },
    { company: 'D3 Soft', role: french ? 'Stage d’initiation' : 'Introductory internship', period: '2023', desc: french ? 'Participation au développement d’une application de gestion de paie : génération de bulletins et gestion des collaborateurs.' : 'Contributing to a payroll-management application, including payslip generation and employee management.', tags: ['Windev', 'MariaDB'], link: 'https://www.d3soft.ma/', image: '/d.png', accent: '#6e98ad' },
  ];
  const copy = french ? { eyebrow: 'JOURNAL D’EXPÉRIENCE', title: <>Apprendre, construire,<br /><i>faire évoluer.</i></>, intro: 'Des expériences concrètes où se rencontrent IA, produit et impact.', current: 'EN CE MOMENT', archive: 'CHAPITRES PRÉCÉDENTS', visit: 'Découvrir ↗' } : { eyebrow: 'EXPERIENCE LOG', title: <>Learn, build,<br /><i>move forward.</i></>, intro: 'Concrete experiences at the intersection of AI, product and impact.', current: 'CURRENTLY', archive: 'PREVIOUS CHAPTERS', visit: 'Discover ↗' };

  return <section id="experiences" className={styles.section}><div className={styles.shell}>
    <header className={styles.header}><p>{copy.eyebrow}</p><h2>{copy.title}</h2><span>{copy.intro}</span></header>
    <div className={styles.leads}>{experiences.slice(0, 2).map((item, index) => <article key={item.company} className={styles.lead} style={{ '--accent': item.accent }}><div className={styles.leadImage}><img src={item.image} alt={item.company} /><span>0{index + 1}</span></div><div className={styles.leadContent}><h3>{item.company}</h3><strong>{item.role}</strong><span>{item.desc}</span><div>{item.tags.map((tag) => <em key={tag}>{tag}</em>)}</div></div></article>)}</div>
    <div className={styles.sectionLabel}><span>{copy.archive}</span><i /></div>
    <div className={styles.archive}>{experiences.slice(2).map((item, index) => <article key={item.company} className={styles.archiveCard} style={{ '--accent': item.accent }}><div className={styles.archiveImage}><img src={item.image} alt={item.company} /></div><div className={styles.archiveTitle}><span>0{index + 3}</span><h3>{item.company}</h3><strong>{item.role}</strong></div><p>{item.desc}</p><div className={styles.archiveBottom}><span>{item.period}</span></div></article>)}</div>
  </div></section>;
}
